//
// Created by Haraoka Shohei on 2018/07/25.
//

#ifndef PITCHANGLECORRECTION_FEATURES_DETECTION_H
#define PITCHANGLECORRECTION_FEATURES_DETECTION_H

#endif //PITCHANGLECORRECTION_FEATURES_DETECTION_H
